resilience4j.circuitbreaker:
  configs:
    default:
        slidingWindowSize: 21
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 100
        minimumNumberOfCalls: 15