package code.codeguru.equinix.soap.oms.shellorder;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "shellOrderService",
                  wsdlLocation = "classpath:soap/shellorder.wsdl",
                  targetNamespace = "http://oms.soap.equinix.codeguru.code/shellorder")
public class ShellOrderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://oms.soap.equinix.codeguru.code/shellorder", "shellOrderService");
    public final static QName ShellOrderInterface = new QName("http://oms.soap.equinix.codeguru.code/shellorder", "shellOrderInterface");
    static {
        URL url = ShellOrderService.class.getClassLoader().getResource("soap/shellorder.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ShellOrderService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:soap/shellorder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShellOrderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShellOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShellOrderService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ShellOrderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ShellOrderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ShellOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ShellOrderInterface
     */
    @WebEndpoint(name = "shellOrderInterface")
    public ShellOrderInterface getShellOrderInterface() {
        return super.getPort(ShellOrderInterface, ShellOrderInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShellOrderInterface
     */
    @WebEndpoint(name = "shellOrderInterface")
    public ShellOrderInterface getShellOrderInterface(WebServiceFeature... features) {
        return super.getPort(ShellOrderInterface, ShellOrderInterface.class, features);
    }

}
