//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 09:46:47 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://oms.soap.equinix.codeguru.code/shellorder", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package code.codeguru.equinix.soap.oms.shellorder;
